const GEOSERVER_URL = import.meta.env.VITE_GEOSERVER_URL.replace(
  '/{baseUrl}',
  import.meta.env.VITE_BASE_URL,
)

export default {
  mapLayers: [
    {
      name: 'sri Imagery',
      nameKey: 'esriImagery',
      default: true,
      key: 'esri',
      url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
    },
    {
      name: 'Sentinel 2',
      default: false,
      key: 'sentinel',
      url: 'https://tiles.maps.eox.at/wmts/1.0.0/s2cloudless-2021_3857/default/g/{z}/{y}/{x}.jpg',
    },
    {
      name: 'OpenStreetMap',
      nameKey: 'openStreetMap',
      default: false,
      key: 'osm',
      url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    },
  ],
  customLayers: [
    {
      name: 'Territorial Division',
      nameKey: 'wms.territorialDivision',
      key: 'dt',
      toggle: { active: 'active', inactive: 'inactive' },
      layers: [
        {
          name: 'Brazil',
          nameKey: 'wms.territorialDivision_layers.brazil',
          baseUrl: GEOSERVER_URL,
          toggle: { active: 'active', inactive: 'inactive' },
          layers: 'rer:PAIS',
          format: 'image/png',
          transparent: true,
          activeDefault: false,
          key: 'dt_brasil',
          style: { color: 'black', fillColor: 'black' },
        },
        {
          name: 'State',
          nameKey: 'wms.territorialDivision_layers.state',
          baseUrl: GEOSERVER_URL,
          toggle: { active: 'active', inactive: 'inactive' },
          layers: 'rer:ESTADOS',
          format: 'image/png',
          transparent: true,
          activeDefault: true,
          key: 'dt_estado',
          style: { color: 'black', fillColor: 'lightblack' },
        },
        {
          name: 'Municipality',
          nameKey: 'wms.territorialDivision_layers.municipality',
          baseUrl: GEOSERVER_URL,
          toggle: { active: 'active', inactive: 'inactive' },
          layers: 'rer:MUNICIPIOS',
          format: 'image/png',
          transparent: true,
          activeDefault: false,
          key: 'dt_municipio',
          style: { color: 'black', fillColor: 'black' },
        },
      ],
    },
    {
      name: 'Declared Rural Properties',
      nameKey: 'wms.declaredRuralProperties',
      key: 'ird',
      toggle: { active: 'active', inactive: 'inactive' },
      layers: [
        {
          name: 'Rural Properties',
          nameKey: 'wms.declaredRuralProperties_layers.ruralProperties',
          baseUrl: GEOSERVER_URL,
          toggle: { active: 'active', inactive: 'inactive' },
          layers: 'rer:RURAL_PROPERTY',
          format: 'image/png',
          transparent: true,
          activeDefault: false,
          key: 'ird_ir',
          style: { color: '#FFFF00', fillColor: '#FFD700' },
        },
        {
          name: 'Consolidated Area',
          nameKey: 'wms.declaredLandCover_layers.consolidatedArea',
          baseUrl: GEOSERVER_URL,
          toggle: { active: 'active', inactive: 'inactive' },
          layers: 'rer:CONSOLIDATED_AREA',
          format: 'image/png',
          transparent: true,
          activeDefault: false,
          key: 'csd_ac',
          style: { color: '#808080', fillColor: '#808080' },
        },
        {
          name: 'Remaining Native Vegetation',
          nameKey: 'wms.declaredLandCover_layers.nativeVegetation',
          baseUrl: GEOSERVER_URL,
          toggle: { active: 'active', inactive: 'inactive' },
          layers: 'rer:REMAINING_NATIVE_VEGETATION',
          format: 'image/png',
          transparent: true,
          activeDefault: false,
          key: 'csd_rvn',
          style: { color: '#008000', fillColor: '#008000' },
        },
        {
          name: 'Legal Reserve',
          nameKey: 'layers.vectorization.legalReserve.displayName',
          baseUrl: GEOSERVER_URL,
          toggle: { active: 'active', inactive: 'inactive' },
          layers: 'rer:LEGAL_RESERVE',
          format: 'image/png',
          transparent: true,
          activeDefault: false,
          key: 'csd_lr',
          style: { color: '#2e7d32', fillColor: '#2e7d32' },
        },
        {
          name: 'River',
          nameKey: 'layers.vectorization.river.displayName',
          baseUrl: GEOSERVER_URL,
          toggle: { active: 'active', inactive: 'inactive' },
          layers: 'rer:RIVER',
          format: 'image/png',
          transparent: true,
          activeDefault: false,
          key: 'csd_riv',
          style: { color: '#1E90FF', fillColor: '#1E90FF' },
        },
        {
          name: 'River (up to 10m)',
          nameKey: 'layers.vectorization.riverUpTo10m.displayName',
          baseUrl: GEOSERVER_URL,
          toggle: { active: 'active', inactive: 'inactive' },
          layers: 'rer:RIVER_UP_TO_10M',
          format: 'image/png',
          transparent: true,
          activeDefault: false,
          key: 'csd_riv10',
          style: { color: '#CFE2F3', fillColor: '#CFE2F3' },
        },
      ],
    },
  ],
  vectorizationGroups: [
    {
      groupName: 'Property',
      groupNameKey: 'layers.vectorization.propertyGroup.groupName',
      groupKey: 'car_imovel_group',
      description: 'Select a layer to draw and process.',
      descriptionKey: 'layers.vectorization.propertyGroup.description',
      layersToVectorize: [
        {
          displayName: 'Rural Property Area',
          displayNameKey: 'layers.vectorization.ruralProperty.displayName',
          layerCode: 'RURAL_PROPERTY',
          description: 'Vectorize the property area.',
          descriptionKey: 'layers.vectorization.ruralProperty.description',
          drawTools: ['polygon'],
          rules: {
            overlap: true,
            geometryType: 'Polygon',
            geometricUnit: 'ha',
            maxInstances: 1,
            required: true,
            style: {
              color: '#FFFF00',
              fillColor: '#FFD700',
              weight: 2,
              fillOpacity: 0.2,
            },
          },
        },
        {
          displayName: 'Property Headquarter',
          displayNameKey: 'layers.vectorization.propertyHeadquarter.displayName',
          layerCode: 'PROPERTY_HEADQUARTERS',
          description: 'Mark the location of the property headquarter.',
          descriptionKey: 'layers.vectorization.propertyHeadquarter.description',
          drawTools: ['marker'],
          rules: {
            overlap: true,
            geometryType: 'Point',
            geometricUnit: 'ha',
            maxInstances: 1,
            required: true,
            style: {
              icon: 'fas fa-thumbtack',
              color: '#FFD700',
              radius: 8,
              weight: 2,
              opacity: 0.8,
              fillColor: '#FFD700',
              fillOpacity: 0.6,
            },
          },
        },
      ],
    },
    {
      groupName: 'Land Cover',
      groupNameKey: 'layers.vectorization.landCoverGroup.groupName',
      groupKey: 'car_land_cover_group',
      description: 'Select a layer to draw and process.',
      descriptionKey: 'layers.vectorization.landCoverGroup.description',
      layersToVectorize: [
        {
          displayName: 'Consolidated Area',
          displayNameKey: 'layers.vectorization.consolidatedAreaVec.displayName',
          layerCode: 'CONSOLIDATED_AREA',
          description: 'Vectorize the consolidated area of the property.',
          descriptionKey: 'layers.vectorization.consolidatedAreaVec.description',
          drawTools: ['polygon'],
          rules: {
            required: false,
            overlap: false,
            geometryType: 'Polygon',
            geometricUnit: 'ha',
            style: {
              color: '#808080',
              fillColor: '#808080',
              weight: 3,
              fillOpacity: 0.5,
            },
          },
        },
        {
          displayName: 'Remaining Native Vegetation',
          displayNameKey: 'layers.vectorization.nativeVegetationVec.displayName',
          layerCode: 'REMAINING_NATIVE_VEGETATION',
          description: 'Vectorize the remaining native vegetation of the property.',
          descriptionKey: 'layers.vectorization.nativeVegetationVec.description',
          drawTools: ['polygon'],
          rules: {
            required: false,
            overlap: false,
            geometryType: 'Polygon',
            geometricUnit: 'ha',
            style: {
              color: '#008000',
              fillColor: '#008000',
              weight: 3,
              fillOpacity: 0.5,
            },
          },
        },
      ],
    },
    {
      groupName: 'Legal Reserve',
      groupNameKey: 'layers.vectorization.legalReserveGroup.groupName',
      groupKey: 'car_legal_reserve_group',
      description: 'Select a layer to draw and process.',
      descriptionKey: 'layers.vectorization.legalReserveGroup.description',
      layersToVectorize: [
        {
          displayName: 'Legal Reserve',
          displayNameKey: 'layers.vectorization.legalReserve.displayName',
          layerCode: 'LEGAL_RESERVE',
          description: 'Vectorize the legal reserve area of the property.',
          descriptionKey: 'layers.vectorization.legalReserve.description',
          drawTools: ['polygon'],
          rules: {
            required: false,
            overlap: false,
            geometryType: 'Polygon',
            geometricUnit: 'ha',
            style: {
              color: '#2e7d32',
              fillColor: '#2e7d32',
              weight: 3,
              fillOpacity: 0.5,
            },
          },
        },
      ],
    },
    {
      groupName: 'Hydrography',
      groupNameKey: 'layers.vectorization.hydrographyGroup.groupName',
      groupKey: 'car_hidrografia_solo_group',
      description: 'Select a layer to draw and process.',
      descriptionKey: 'layers.vectorization.hydrographyGroup.description',
      layersToVectorize: [
        {
          displayName: 'River',
          displayNameKey: 'layers.vectorization.river.displayName',
          layerCode: 'RIVER',
          description: 'Vectorize the river area of the property.',
          descriptionKey: 'layers.vectorization.river.description',
          tooltip: 'layers.vectorization.river.tooltip',
          drawTools: ['polygon'],
          rules: {
            required: false,
            maxInstances: 1,
            overlap: true,
            geometryType: 'Polygon',
            geometricUnit: 'ha',
            style: {
              color: '#1E90FF',
              fillColor: '#1E90FF',
              weight: 2,
              fillOpacity: 0.2,
            },
            buffer: {
              layerCode: 'PPA_WIDER_THAN_10M',
              style: {
                color: '#FF8C00',
                weight: 3,
                opacity: 0.8,
                fillColor: '#FF8C00',
                fillOpacity: 0.25,
              },
            },
          },
        },
        {
          displayName: 'River (up to 10m)',
          displayNameKey: 'layers.vectorization.riverUpTo10m.displayName',
          layerCode: 'RIVER_UP_TO_10M',
          description: 'Vectorize the river area of the property.',
          descriptionKey: 'layers.vectorization.riverUpTo10m.description',
          tooltip: 'layers.vectorization.riverUpTo10m.tooltip',
          drawTools: ['polyline'],
          rules: {
            required: false,
            maxInstances: 1,
            overlap: true,
            geometryType: 'LineString',
            lineMaxLength: 10,
            geometricUnit: 'm',
            style: {
              color: '#CFE2F3',
              fillColor: '#CFE2F3',
              weight: 2,
              fillOpacity: 0.2,
            },
            buffer: {
              layerCode: 'PPA_UP_TO_10M',
              style: {
                color: '#FF8C00',
                weight: 3,
                opacity: 0.8,
                fillColor: '#FF8C00',
                fillOpacity: 0.25,
              },
            },
          },
        },
      ],
    },
  ],
}
