services:

  core-frontend:
    image: rer-frontend:latest
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - APP_VERSION=0.0.0
    container_name: core-frontend
    restart: unless-stopped
    networks:
      # - frontend_network
      - gateway_network